baseURL = 'https://likontech.github.io/'
# languageCode = "zh"
# defaultContentLanguage = "zh"
title = "likon"                        # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 10
paginate = 4                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
# googleAnalytics = ""                   # your google analytics id       # Google统计代码
# disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "likon"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "岁岁年，碎碎念"                                       # site's subTitle              # 网站二级标题
  keywords = ["likon","碎碎念","记录"]                                   # site's keywords              # 网站关键字
  description = "likon 的个人技术博客网站，主要专注大前端，记录技术、所思所想"                        # site's description           # 网站描述
  enableMathJax = true                                                 # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = false                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  # footerSlogan = "学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？"                                   # site's footer slogan         # 网站页脚标语

# 不蒜子
[params.busuanzi]
  enable = true

# 评论
[params.utterances]
  enable = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true